# Generated by Django 4.0 on 2021-12-08 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Puroduct',
            new_name='Product',
        ),
    ]
